# Development container - todo_app should be mounted as a bind mount to watch for changes.
FROM python:3.9-slim-bullseye
RUN apt-get update 
RUN apt-get -y install wget
RUN wget -O install-poetry.py https://install.python-poetry.org
RUN python install-poetry.py -y
ENV PATH="/root/.local/bin:$PATH"


WORKDIR /opt/todoapp

ENV FLASK_APP=todo_app/app
ENV FLASK_ENV=development

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
RUN poetry install

COPY scripts scripts

ENTRYPOINT ["/bin/bash", "-c",  "poetry run flask run --host 0.0.0.0"]