name: Docker Image CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Touch the env file 
      run: touch deployment_files/.env
    - name: Build the Docker image
      run: docker compose build todo-app-test
    - name: Run the tests
      run: docker compose up todo-app-test
